### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by bjoerns1983** [xoseperez/node-red-contrib-power-monitor#12]
First of all i really like this node and i use it now more than a year for my washing machine etc.
Only problem i have now is that v 1.0.0 simply breaks all my flows because it works completely different than v.0.1.2.

The problem is that there was not even a warning in the readme etc. and the node red palette does not have a simple way to revert back to 0.1.2.
I think it would have been more conveniant to make an v2 of the Power Monitor Node  or to have the old style node included as a legacy solution.

Nevertheless, i think you should change the Readme so the user are warned that this update might break something.

**Comment by xoseperez** [comment]
I'm sorry for the incovenience.
The update follows the [semantic versioning](https://semver.org/) approach where changes to the major (first number) indicates possible backwards compatibility issues.
But you are right a notice to the README should be added to notify of the changes and possible fixes to existing flows. Adding this as an improvement.
Thank you!
