### ISSUE TITLE
Whole house power meter analysis

### ISSUE THREAD

**Issue by 8666** [xoseperez/node-red-contrib-power-monitor#2]
This is an interesting project but rather basic.

Is it possible to feed it with the consumption of whole house power meter so it can determine what appliances are used? 

Usually, large ones will make quite big changes so they can be easily distinguished. The user can provide a list of appliances and their usage so the node can find out the closest match.

There is a commercial project that can fingerprint devices based on their power usage patterns, but I do not think anything like that is available as open source

**Comment by xoseperez** [comment]
No, that's not the goal of this node. It is indeed basic, as you say, but focused on monitoring a single device.

I know some project that do as you say. They usually require frequent data feeding (like 1Hz) and they claim to be able to identify not only what appliance you are using but also it's status (like tellling you the fridge is not performing well, so it might require maintenance).
