### ISSUE TITLE
Output from node - Current kWh Usage

### ISSUE THREAD

**Issue by beccsjb** [xoseperez/node-red-contrib-power-monitor#4]
I think this node is great, the only one of its kind.
Most little issues you can work around and its been great. However, itd really like to see the kWh count being pushed out another output so that you dont have to wait until the end of the "Usage" Window to see the data.  The node is obviously capable of it as it does it and you can see it in the editor.

**Comment by buzzshot** [comment]
I agree. This is a very nice node, but it would be nice to push out the data at least once every hour then you could push it to a database. something like influxdb to map power monitoring.

**Comment by xoseperez** [comment]
This will be added with #8
