### ISSUE TITLE
Why energy output divided by 360 and 10.000?

### ISSUE THREAD

**Issue by Ralf31337** [xoseperez/node-red-contrib-power-monitor#5]
Hello, I am struggling with the node and thats why I took a look at the code:
kwh(x) = x / 360 / 10000

I was expecting that msg.payload.energy contains the sum of all inputs between start and stop. For me it contains a very small number when I run it in my flows?

The above function looks like it was meant to divide by 3600 (hour?) and then 1000 to make W to kWh?

**Comment by xoseperez** [comment]
Input is watts and the running energy sum contains the integral of that value, thus watts·seconds or joules. 

1kWh * (1000W/1kW) * (3600s/1h) = 3600000 Ws.

I don't recall why I wrote it that way but the numbers are the same.

**Comment by xoseperez** [comment]
Actually it's not exactly as you copied:

```
function kwh(value) {
    return Math.round(value / 360) / 10000;
}
```
So the original idea was to have a resolution down to a tenth of Wh.
