### ISSUE TITLE
Start/Stop by time

### ISSUE THREAD

**Issue by JorgeMaTeixeira** [xoseperez/node-red-contrib-power-monitor#6]
To have more flexibility, knowing that some appliances (like washing machines and more) have a super variable power consumption during the cycle, reaching sometimes 0 o very close to 0w, i think that the option to use time insted of x readings over/below the threshould could facilitate in some situations. 

My sugestion is start/stop after x time over/below the threshould .

**Comment by xoseperez** [comment]
Given that you know the rate at which data is fed into the node, I don't see a difference betweenyour suggestion and the current way it works. If you want to trigger the start event after 5 minutes above threshold, and you are feeding data every minute, a starttime of 5 would do the trick...
